spring.application.name=fileuploadservice
spring.config.import=optional:file:.env[.properties]
#spring.main.banner-mode=off
spring.output.ansi.enabled=ALWAYS

#Http Configuration
spring.mvc.apiversion.use.header=X-API-Version
app.cors.allowed-origins=${CORS}


# --- Server ---
server.port=8081

clamav.host=${CLAMAV_HOST:localhost}
clamav.port=${CLAMAV_PORT:3310}
clamav.timeout=${CLAMAV_TIMEOUT:300000}


# --- Database Configuration ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.connectionTimeout=${CONN_TIMEOUT}
spring.datasource.hikari.maximumPoolSize=${POOL_MAXSIZE}


# --- Security Configuration ---
spring.security.user.name=${SEC_USERNAME}
spring.security.user.password=${SEC_PASSWORD}
#logging.level.org.springframework.security=DEBUG


# --- AWS INTEGRATION ---
cloud.aws.accessKey=${CLOUD_ACCESSKEY}
cloud.aws.secretKey=${CLOUD_SECRETKEY}
cloud.aws.region=${CLOUD_REGION}
cloud.aws.keypair=${KEY_PAIR}
aws.valid-bucket.name=${VALIDATION_BUCKET}
aws.game-bucket.name=${GAME_BUCKET}
aws.image-bucket.name=${IMG_BUCKET}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-request-size=1GB
spring.servlet.multipart.max-file-size=1GB
ServicePointManager.DefaultConnectionLimit=25
server.tomcat.max-swallow-size=20MB
server.tomcat.disable-upload-timeout=false
server.tomcat.connection-upload-timeout=1800000
server.connection-timeout=1800000
spring.mvc.async.request-timeout=1800000
spring.servlet.multipart.resolve-lazily=true